### ISSUE TITLE
코드 수정 요청 사항

### ISSUE THREAD

**Issue by snoopspy** [le3mon/add_nbo#1]
https://github.com/le3mon/add_nbo/commit/cd5fb08a65b5de533635bd8207dd51d530803d80#r38107046

https://github.com/le3mon/add_nbo/commit/cd5fb08a65b5de533635bd8207dd51d530803d80#r38107040

**Comment by le3mon** [comment]
https://github.com/le3mon/add_nbo/commit/3ecc9582e5455db52db4fb194001a7412b449b4f
수정 했습니다.
